FROM node:20-alpine AS build

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . ./
RUN npm run build

FROM node:20-alpine

WORKDIR /app
COPY --from=build /app/dist /app/dist

CMD ["sh", "-c", "cp -r /app/dist/* /dist && tail -f /dev/null"]
